services:
  frontend:
    build: ./frontend
    container_name: nextjs-app
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: "http://backend:8080"
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: springboot-api
    ports:
      - "8080:8080"
    environment:
      # For NEON Postgres:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ep-purple-sky-aex6jkne-pooler.c-2.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      SPRING_DATASOURCE_USERNAME: neondb_owner
      SPRING_DATASOURCE_PASSWORD: npg_YBrNDEwXxQ38

      # If using MongoDB instead:
      # SPRING_DATA_MONGODB_URI: mongodb+srv://<user>:<password>@cluster.mongodb.net/<db>
